# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool: Default
  #vmImage: 'macos-latest'

steps:
  # sync
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm i'

  # sync
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'ionic capacitor sync android'

  # unit test
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm run test:unit'

  # build debug
- task: Gradle@2
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'
