# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

variables:
  vmImageName: Default
  projectName: 'CITest'

stages:
  - stage: Build
    displayName: Build Ionic - Android projects
    jobs:
      # Debug build
      - job: Build_Ionic_Android_Debug
        variables:
          - name: buildConfiguration
            value: Debug
        displayName: Build Debug
        pool:
          vmImage: $(vmImageName)
        steps:
          - template: ionic-android-debug-build.yml

      # Release build
      #- job: Build_Ionic_Android_Release
      #  variables:
      #    - name: buildConfiguration
      #      value: Release
      #  displayName: Build Release
      #  pool:
      #    vmImage: $(vmImageName)
      #  steps:
      #    - template: ionic-android-release-build.yml